version: '2'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        GID: 1001
        UID: 1001
        TZ: Europe/Paris
        PROXY: null
        NO_PROXY: null
